AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  deytlambdajsonparquet:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 123
      Role: 'arn:aws:iam::385740189677:role/de-yt-lambda-s3-role'
      Environment:
        Variables:
          glue_catalog_db_name: de-yt-clean
          glue_catalog_table_name: clean_statistics_reference_data
          s3_cleansed_layer: 's3://de-yt-data-cleansed/youtube/'
          write_data_operation: append
      Layers:
        - 'arn:aws:lambda:us-east-1:336392948345:layer:AWSDataWrangler-Python38:2'
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
